name: state_view_widget
description: "StatefulWidget on steroids"
version: 0.0.1
homepage: https://github.com/MohiuddinM/state_view_widget.git

environment:
  sdk: ^3.6.0-334.2.beta
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.3-main.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
